import { WorkbenchPanel, useWorkbenchView } from "./WorkbenchFrame";
import {enUS} from "./i18n/en-US";
import {useEffect,useImperativeHandle,useRef,useState,type Ref} from "react";
import * as Dialog from "@radix-ui/react-dialog";
import {useTranslation} from "react-i18next";
import type {CommandError,ProjectView} from "./projectCommands";
import {executionCommands as execution,executionContext,type PrepareRequest} from "./executionCommands";
import {sourceCommands,type ContentPage} from "./sourceCommands";
import {aiCommands,aiTarget,defaultAiConfig,type AiConfig,type AiPrepared,type AiStart,type AiView} from "./aiCommands";
import type {EditorTarget} from "./TranslationWorkbench";
export interface AiHandle {allowLeave:()=>Promise<boolean>;showAttempt:(id:string)=>void}
const stage=(e:unknown)=>{const value=e as Partial<CommandError>|null;return value?.field??value?.code??"outcome-unknown";};
export function AiWorkbench({project,disabled,ref,onOpenTranslation}:{project:ProjectView;disabled:boolean;ref?:Ref<AiHandle>;onOpenTranslation:(target:EditorTarget,locale:string)=>boolean}) {
  const {t}=useTranslation();const context=executionContext(project);
  const [connectionOpen,setConnectionOpen]=useState(true);
  const [presetName,setPresetName]=useState("custom");const [open,setOpen]=useWorkbenchView("ai"),[config,setConfig]=useState<AiConfig>(()=>({...defaultAiConfig}));
  const [locale,setLocale]=useState(project.metadata.targetLocales[0]??""),[page,setPage]=useState<ContentPage|null>(null),[selected,setSelected]=useState<string[]>([]);
  const [prepared,setPrepared]=useState<AiPrepared|null>(null),[consent,setConsent]=useState(false),[attempt,setAttempt]=useState<string|null>(null),[view,setView]=useState<AiView|null>(null);
  const [busy,setBusy]=useState(false),[failure,setFailure]=useState<string|null>(null),[dirty,setDirty]=useState(false),[leaving,setLeaving]=useState(false);
  const [pendingStart,setPendingStart]=useState<AiStart|null>(null),[pendingAdopt,setPendingAdopt]=useState<PrepareRequest|null>(null),[receiptMissing,setReceiptMissing]=useState(false);
  const alive=useRef(true),generation=useRef(0),inFlight=useRef(false),leaveResolve=useRef<((v:boolean)=>void)|null>(null),errorRef=useRef<HTMLDivElement>(null);
  const active=!!attempt&&(!view||view.detail.progress.queued>0||view.detail.progress.running>0);
  const locked=busy||!!pendingStart||!!pendingAdopt||active;
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;leaveResolve.current?.(false);};},[]);
  useEffect(()=>{if(failure){if(["ai-endpoint","ai-model","ai-credential"].includes(failure))setConnectionOpen(true);errorRef.current?.focus();}},[failure]);
  async function perform(work:(current:()=>boolean)=>Promise<void>) {
    if(inFlight.current)return;inFlight.current=true;setBusy(true);setFailure(null);
    const ticket=++generation.current;const current=()=>alive.current&&generation.current===ticket;
    try{await work(current);}catch(e){if(current())setFailure(stage(e));}
    finally{inFlight.current=false;if(alive.current)setBusy(false);}
  }
  function allowLeave():Promise<boolean> {
    if(inFlight.current||pendingStart||pendingAdopt){setOpen(true);setFailure("outcome-unknown");return Promise.resolve(false);}
    if(!dirty)return Promise.resolve(true);
    setOpen(true);setLeaving(true);return new Promise(resolve=>{leaveResolve.current?.(false);leaveResolve.current=resolve;});
  }
  function settleLeave(value:boolean){setLeaving(false);if(value){setDirty(false);setPresetName("custom");setConfig({...defaultAiConfig});setLocale(project.metadata.targetLocales[0]??"");setSelected([]);setPrepared(null);setConsent(false);setAttempt(null);setView(null);setOpen(false);}leaveResolve.current?.(value);leaveResolve.current=null;}
  useImperativeHandle(ref,()=>({allowLeave,showAttempt(id){if(dirty||inFlight.current||pendingStart||pendingAdopt){setOpen(true);return;}setAttempt(id);setView(null);setOpen(true);}}));
  async function loadPage(after=0) {
    await perform(async current=>{const scope=await sourceCommands.scope(context);if(!scope.currentSnapshot){if(current())setPage(null);return;}const result=await sourceCommands.content({...context,snapshotId:scope.currentSnapshot,after,limit:50});if(current())setPage(result);});
  }
  useEffect(()=>{if(open&&!page)void loadPage();},[open]);
  useEffect(()=>{
    if(!open||!attempt||busy)return;
    let stopped=false;let timer:ReturnType<typeof setTimeout>|undefined;
    const ticket=generation.current;
    async function poll(){try{const result=await aiCommands.read({...context,attemptId:attempt!});if(!stopped&&alive.current&&generation.current===ticket){setView(result);setFailure(previous=>previous==="busy"?null:previous);if(!result.detail.progress.queued&&!result.detail.progress.running)return;}}catch(e){if(!stopped&&alive.current&&generation.current===ticket&&stage(e)!=="busy")setFailure(stage(e));}if(!stopped)timer=setTimeout(()=>void poll(),1500);}
    void poll();return()=>{stopped=true;clearTimeout(timer);};
  },[open,attempt,busy,project.sessionToken]);
  function change<K extends keyof AiConfig>(key:K,value:AiConfig[K]){setFailure(null);setConfig(c=>({...c,[key]:value}));setPrepared(null);setConsent(false);setDirty(true);}
  function preset(value:string){setFailure(null);setPresetName(value);setConfig(c=>({...c,endpoint:value==="openai"?"https://api.openai.com/v1/chat/completions":value==="local"?"http://127.0.0.1:11434/v1/chat/completions":"",credentialEnv:value==="local"?"":"OPENAI_API_KEY",tokenField:value==="openai"?"max_completion_tokens":"max_tokens"}));setPrepared(null);setConsent(false);setDirty(true);}
  async function start(request:AiStart,current:()=>boolean){setPendingStart(request);try{const id=await aiCommands.start(request);if(current()){setAttempt(id);setPendingStart(null);setPrepared(null);setConsent(false);setView(null);setDirty(false);}}catch(e){if(current()&&!stage(e).includes("unknown"))setPendingStart(null);throw e;}}
  async function adopt(request:PrepareRequest,current:()=>boolean){setPendingAdopt(request);setReceiptMissing(false);try{await execution.prepare(request);await execution.adopt({...context,actionId:request.actionId});const next=await aiCommands.read({...context,attemptId:request.attemptId});if(current()){setView(next);setPendingAdopt(null);}}catch(e){if(current()&&!stage(e).includes("unknown"))setPendingAdopt(null);throw e;}}
  const numeric=[['maxItems',1,100],['concurrency',1,2],['maxRequests',1,300],['maxOutputTokens',1,16384],['maxRetries',0,2],['timeoutSeconds',1,120]] as const;
  const fieldFailure=(key:string)=>failure===`ai-${key==="credentialEnv"?"credential":key}`;
  const fieldError=(key:string)=>fieldFailure(key)?<span id={`ai-error-${key}`} className="field-error">{t(`ai.errors.${failure}`,{defaultValue:t("ai.errors.failed")})}</span>:null;
  return <><WorkbenchPanel open={open} title={t("ai.title")} description={t("ai.description")} className="ai-dialog" onBack={()=>void allowLeave().then(ok=>{if(ok)setOpen(false);})} backDisabled={disabled || busy || !!pendingStart || !!pendingAdopt}>
    {failure?<div role="alert" tabIndex={-1} ref={errorRef}><p>{t(`ai.errors.${failure}`,{defaultValue:t("ai.errors.failed")})}</p><button className="secondary-button" onClick={()=>void loadPage()} disabled={busy}>{t("ai.refresh")}</button></div>:null}
    <fieldset disabled={locked}><legend>{t("ai.scope",{count:selected.length})}</legend><details open={connectionOpen} onToggle={event=>setConnectionOpen(event.currentTarget.open)}><summary>{t("ai.connection")}</summary><label className="field">{t("ai.preset")}<select value={presetName} onChange={e=>preset(e.target.value)}><option value="custom">{t("ai.custom")}</option><option value="openai">OpenAI</option><option value="local">{t("ai.local")}</option></select></label>
    {([['endpoint','url'],['model','text'],['credentialEnv','text']] as const).map(([key,type])=><label className="field" key={key}>{t(`ai.${key}`)}<input type={type} value={config[key]} aria-label={t(`ai.${key}`)} aria-invalid={fieldFailure(key)||undefined} aria-describedby={fieldFailure(key)?`ai-error-${key}`:undefined} onChange={e=>change(key,e.target.value)}/>{fieldError(key)}</label>)}<p>{t("ai.credentialHelp")}</p>
    <label className="field">{t("ai.tokenField")}<select value={config.tokenField} onChange={e=>change("tokenField",e.target.value)}><option value="max_tokens">max_tokens</option><option value="max_completion_tokens">max_completion_tokens</option></select></label>
    </details><details open={failure==="ai-limits"?true:undefined}><summary>{t("ai.budget")}</summary>{failure==="ai-limits"?<p id="ai-error-limits" className="field-error">{t("ai.errors.ai-limits")}</p>:null}{numeric.map(([key,min,max])=><label className="field" key={key}>{t(`ai.${key}`)}<input type="number" min={min} max={max} value={Number.isFinite(config[key])?config[key]:""} aria-invalid={failure==="ai-limits"&&(!Number.isInteger(config[key])||config[key]<min||config[key]>max)||undefined} aria-describedby={failure==="ai-limits"?"ai-error-limits":undefined} onChange={e=>change(key,e.target.valueAsNumber)}/></label>)}<button className="secondary-button" type="button" onClick={()=>{setFailure(null);setConfig(c=>({...defaultAiConfig,endpoint:c.endpoint,model:c.model,credentialEnv:c.credentialEnv,tokenField:c.tokenField}));setPrepared(null);setConsent(false);setDirty(true);}}>{t("ai.reset")}</button></details>
    <label className="field">{t("ai.locale")}<select value={locale} onChange={e=>{setLocale(e.target.value);setPrepared(null);setConsent(false);setDirty(true);}}>{project.metadata.targetLocales.map(l=><option key={l}>{l}</option>)}</select></label>
    <label className="source-check"><input type="checkbox" checked={config.shareTerms} onChange={e=>change("shareTerms",e.target.checked)}/>{t("ai.shareTerms")}</label><label className="source-check"><input type="checkbox" checked={config.shareContext} onChange={e=>change("shareContext",e.target.checked)}/>{t("ai.shareContext")}</label>
    <h3>{t("ai.scope",{count:selected.length})}</h3>{page?<><ul>{page.rows.map(row=>row.unitId?<li key={row.unitId}><label className="source-check"><input type="checkbox" checked={selected.includes(row.unitId)} onChange={e=>{setSelected(ids=>e.target.checked?[...ids,row.unitId!]:ids.filter(id=>id!==row.unitId));setPrepared(null);setConsent(false);setDirty(true);}}/>{row.occurrence.key}: {row.occurrence.text}</label></li>:null)}</ul><button className="secondary-button" disabled={locked} onClick={()=>void loadPage(0)}>{t("ai.first")}</button>{page.nextOrdinal!==null?<button className="secondary-button" onClick={()=>void loadPage(page.nextOrdinal!)}>{t("ai.next")}</button>:null}</>:<p>{t("ai.noSource")}</p>}
    <button className="primary-button" disabled={!selected.length} onClick={()=>void perform(async current=>{if(numeric.some(([key,min,max])=>!Number.isInteger(config[key])||config[key]<min||config[key]>max))throw {field:"ai-limits"};const result=await aiCommands.preview({...context,config,locale,unitIds:selected});if(current()){setPrepared(result);setConsent(false);}})}>{t("ai.preview")}</button></fieldset>
    {prepared?<section><h3>{t("ai.previewTitle")}</h3><p>{prepared.preview.config.endpoint} · {prepared.preview.config.model}</p><p>{t("ai.limits",{defaultValue:enUS.ai.limits,requests:config.maxRequests,concurrency:config.concurrency,tokens:config.maxOutputTokens,retries:config.maxRetries})}</p><p>{t("ai.costUnknown")}</p>{prepared.preview.items.map(item=><article key={item.unitId}><h4>{item.nativeKey} → {item.targetLocale}</h4><pre className="ai-text">{item.sourceText}</pre>{item.terms.map(term=><p key={term.revisionId}>{term.source} → {term.target}</p>)}{item.context?<pre className="ai-text">{item.context.text}</pre>:null}{item.omissions.map(reason=><p key={reason}>{reason.startsWith("term-conflict:")?t("ai.termConflict",{term:reason.slice(14)}):t(`ai.${reason}`,{defaultValue:reason})}</p>)}</article>)}<label className="source-check"><input type="checkbox" checked={consent} disabled={locked} onChange={e=>setConsent(e.target.checked)}/>{t("ai.consent")}</label><button className="primary-button" disabled={locked||!consent} onClick={()=>void perform(current=>start({...context,attemptId:prepared.attemptId,digest:prepared.preview.digest,confirmed:true},current))}>{t("ai.generate")}</button></section>:null}
    {pendingStart?<section role="status"><p>{t("ai.startUnknown")}</p><button className="secondary-button" disabled={busy} onClick={()=>void perform(async current=>{const result=await aiCommands.read({...context,attemptId:pendingStart.attemptId});if(current()){setView(result);setAttempt(pendingStart.attemptId);setPendingStart(null);setPrepared(null);setConsent(false);setDirty(false);}})}>{t("ai.reconcile")}</button><button className="secondary-button" disabled={busy} onClick={()=>void perform(current=>start(pendingStart,current))}>{t("ai.retrySame")}</button></section>:null}
    {pendingAdopt?<section><p>{t("ai.adoptUnknown")}</p><button className="secondary-button" disabled={busy} onClick={()=>void perform(async current=>{const receipt=await execution.receipt({...context,actionId:pendingAdopt.actionId});if(receipt){const next=await aiCommands.read({...context,attemptId:pendingAdopt.attemptId});if(current()){setPendingAdopt(null);setView(next);}}else if(current())setReceiptMissing(true);})}>{t("ai.reconcile")}</button>{receiptMissing?<button className="secondary-button" disabled={busy} onClick={()=>void perform(current=>adopt(pendingAdopt,current))}>{t("ai.retrySame")}</button>:null}</section>:null}
    {view?<section><h3>{t("ai.results")}</h3><p>{view.config.model} · {view.recipe}</p><p>{t("ai.progress",{...view.detail.progress,defaultValue:enUS.ai.progress})}</p>{active?<button className="secondary-button" disabled={busy} onClick={()=>void perform(async current=>{await execution.cancel({...context,taskId:view.detail.taskId,requestId:await execution.identity(context)});if(current())setView(await aiCommands.read({...context,attemptId:view.detail.attemptId}));})}>{t("ai.cancel")}</button>:null}<button className="secondary-button" disabled={busy} onClick={()=>void perform(async current=>{const result=await aiCommands.read({...context,attemptId:view.detail.attemptId});if(current())setView(result);})}>{t("ai.refresh")}</button>
    {view.rows.map(row=>{const item=view.detail.items.find(i=>i.status.itemId===row.itemId);const unit=view.detail.recovery.units.find(u=>u.itemIds.includes(row.itemId));return <article key={row.itemId}><h4>{row.item.nativeKey}</h4><p>{t(`ai.states.${item?.status.execution}`,{defaultValue:item?.status.execution??""})}</p>{item?.status.diagnostic?<p>{t(`ai.errors.${item.status.diagnostic}`,{defaultValue:t("ai.errors.failed")})}</p>:null}{row.output?<><pre className="ai-text">{row.output.text}</pre><p>{row.output.usage?t("ai.usage",{...row.output.usage,defaultValue:enUS.ai.usage}):t("ai.usageUnknown")}{row.output.usage&&row.output.usageIncomplete?` · ${t("ai.usageUnknown")}`:""}</p><button className="secondary-button" disabled={busy||!!pendingAdopt||item?.status.adoption==="committed"||!unit} onClick={()=>void perform(async current=>adopt({...context,attemptId:view.detail.attemptId,unitId:unit!.unitId,actionId:await execution.identity(context),resultIds:[row.resultId!]},current))}>{item?.status.adoption==="committed"?t("ai.saved"):t("ai.saveCandidate")}</button><button className="secondary-button" disabled={busy||!!pendingAdopt} onClick={()=>void allowLeave().then(ok=>{if(ok&&onOpenTranslation(aiTarget(row.item),row.item.targetLocale))setOpen(false);})}>{t("ai.openEditor")}</button></>:null}</article>;})}<p>{t("ai.noAutomaticRetry")}</p></section>:null}

  </WorkbenchPanel><Dialog.Root open={leaving} onOpenChange={next=>{if(!next)settleLeave(false);}}><Dialog.Portal><Dialog.Overlay className="dialog-backdrop execution-confirm-backdrop"/><Dialog.Content className="confirm-dialog execution-confirm-dialog"><Dialog.Title>{t("ai.unsaved")}</Dialog.Title><Dialog.Description>{t("ai.unsavedDescription")}</Dialog.Description><button className="secondary-button" onClick={()=>settleLeave(false)}>{t("ai.stay")}</button><button className="secondary-button" onClick={()=>settleLeave(true)}>{t("ai.discard")}</button></Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
