import { useSessionQuery } from "./SessionReadProvider";
import { hasUnknownOutcome } from "./projectCommands";
import { WorkbenchPanel, useWorkbenchView } from "./WorkbenchFrame";
import {useEffect,useImperativeHandle,useRef,useState,type Ref} from "react";
import * as Dialog from "@radix-ui/react-dialog";
import {useTranslation} from "react-i18next";
import {enUS} from "./i18n/en-US";
import type {CommandError,ProjectView} from "./projectCommands";
import {executionCommands as execution,executionContext,type PrepareRequest,type CancelRequest} from "./executionCommands";
import {sourceCommands,type ContentPage} from "./sourceCommands";
import {aiTarget,defaultAiConfig,type AiConfig,type AiStart} from "./aiCommands";
import {arenaCommands as arena,defaultArenaConfig,type ArenaConfig,type ArenaPrepared,type ArenaView,type ComparisonView,type ComparisonSummary,type CompareRequest,type MergeRequest} from "./arenaCommands";
import {translationCommands as translations,type TranslationHistory,type TranslationSelectRequest} from "./translationCommands";
import type {AiHandle} from "./AiWorkbench";
import type {EditorTarget} from "./TranslationWorkbench";

type Pending={kind:"start";request:AiStart}|{kind:"adopt";request:PrepareRequest}|{kind:"compare";request:CompareRequest}|{kind:"merge";request:MergeRequest}|{kind:"select";request:TranslationSelectRequest}|{kind:"cancel";request:CancelRequest;attemptId:string}|{kind:"reveal";request:{sessionToken:string;projectId:string;comparisonId:string;actionId:string}};
const stage=(e:unknown)=>{const v=e as Partial<CommandError>|null;return v?.code==="outcome-unknown"?"outcome-unknown":v?.reason??v?.field??v?.code??"outcome-unknown";};
const unknown=hasUnknownOutcome;
const letter=(i:number)=>String.fromCharCode(65+i);

export function ArenaWorkbench({project,disabled,ref,onOpenTranslation}:{project:ProjectView;disabled:boolean;ref?:Ref<AiHandle>;onOpenTranslation:(target:EditorTarget,locale:string)=>boolean}) {
 const {t}=useTranslation(),context=executionContext(project);
 const [open,setOpen]=useWorkbenchView("arena"),[config,setConfig]=useState<ArenaConfig>(defaultArenaConfig),[locale,setLocale]=useState(project.metadata.targetLocales[0]??"");
 const [page,setPage]=useState<ContentPage|null>(null),[selected,setSelected]=useState<string[]>([]),[unit,setUnit]=useState("");
 const [prepared,setPrepared]=useState<ArenaPrepared|null>(null),[consent,setConsent]=useState(false),[attempt,setAttempt]=useState<string|null>(null);
 const [history,setHistory]=useState<TranslationHistory|null>(null),[references,setReferences]=useState<string[]>([]),[comparison,setComparison]=useState<ComparisonView|null>(null),[savedComparisons,setSavedComparisons]=useState<ComparisonSummary[]>([]);
 const [comparisonBlind,setComparisonBlind]=useState(false);
 const [draft,setDraft]=useState<{basis:ComparisonView;text:string}|null>(null),draftRef=useRef(draft);draftRef.current=draft;
 const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[failure,setFailure]=useState<string|null>(null),[pollFailure,setPollFailure]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[pending,setPending]=useState<Pending|null>(null),[retryReady,setRetryReady]=useState(false),[leaving,setLeaving]=useState(false);
 const alive=useRef(true),generation=useRef(0),flight=useRef(false),leaveResolve=useRef<((v:boolean)=>void)|null>(null),errorRef=useRef<HTMLDivElement>(null);
 const viewRead = useSessionQuery<ArenaView | null>({
   key: ["arena", attempt], scopes: ["execution", "source", "translation", "resources", "arena"], enabled: open && !!attempt && !busy,
   read: () => arena.read({...context, attemptId: attempt!}),
 });
 const view = viewRead.data ?? null, setView = viewRead.setData;
 const active=!!attempt&&(!view||view.detail.progress.queued>0||view.detail.progress.running>0),locked=busy||!!pending||active;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;leaveResolve.current?.(false);};},[]);
 const displayedFailure=failure??pollFailure;
 useEffect(()=>{if(displayedFailure)errorRef.current?.focus();},[displayedFailure]);
 async function perform(work:(current:()=>boolean)=>Promise<void>) {if(flight.current)return;flight.current=true;setBusy(true);setFailure(null);setPollFailure(null);const ticket=++generation.current,current=()=>alive.current&&generation.current===ticket;try{await work(current);}catch(e){if(current())setFailure(stage(e));}finally{flight.current=false;if(alive.current)setBusy(false);}}
 function allowLeave():Promise<boolean>{if(flight.current||pending){setOpen(true);setFailure("outcome-unknown");return Promise.resolve(false);}if(!dirty&&!draft)return Promise.resolve(true);setOpen(true);setLeaving(true);return new Promise(resolve=>{leaveResolve.current?.(false);leaveResolve.current=resolve;});}
 function settleLeave(value:boolean){setLeaving(false);if(value){setDirty(false);setDraft(null);setConfig(defaultArenaConfig());setComparisonBlind(false);setReferences([]);setPrepared(null);setConsent(false);setOpen(false);}leaveResolve.current?.(value);leaveResolve.current=null;}
 useImperativeHandle(ref,()=>({allowLeave,showAttempt(id){setOpen(true);if(dirty||draft||flight.current||pending){setFailure("arena-draft");return;}setAttempt(id);setView(null);}}));
 function changed(next:ArenaConfig){setConfig(next);setPrepared(null);setConsent(false);setDirty(true);}
 function variant(slot:number,key:keyof AiConfig,value:string|number|boolean){changed({...config,variants:config.variants.map((v,i)=>i===slot?{...v,[key]:value}:v)});}
 async function refreshPage(after=0){await perform(async current=>{const scope=await sourceCommands.scope(context);const next=scope.currentSnapshot?await sourceCommands.content({...context,snapshotId:scope.currentSnapshot,after,limit:50}):null;const comparisons=await arena.comparisons(context);if(current()){setPage(next);setSavedComparisons(comparisons);}});}
 useEffect(()=>{if(open&&!page)void refreshPage();},[open]);
 useEffect(()=>{if(viewRead.error)setPollFailure(stage(viewRead.error));else if(viewRead.isSuccess)setPollFailure(null);},[viewRead.error,viewRead.isSuccess]);
 async function loadHistory(id:string,afterOrdinal="0"){
  if(!id){setUnit("");setHistory(null);setComparison(null);setReferences([]);return;}
  const more=afterOrdinal!=="0"&&id===unit&&history?.locale===locale;
  await perform(async current=>{
   const next=await translations.history({...context,unitId:id,locale,afterOrdinal,limit:50});
   if(current()){
    setUnit(id);setHistory(old=>more&&old?{...next,rows:[...old.rows,...next.rows.filter(row=>!old.rows.some(prior=>prior.revisionId===row.revisionId))]}:next);
    setComparison(null);if(!more)setReferences([]);
   }
  });
 }
 async function refreshResult(current:()=>boolean){if(attempt){const next=await arena.read({...context,attemptId:attempt});if(current())setView(next);}if(comparison?.comparisonId){const next=await arena.comparison({...context,comparisonId:comparison.comparisonId});if(current())setComparison(next);}}
 async function mutate(action:Pending,current:()=>boolean){setPending(action);setRetryReady(false);setNotice(null);let committed=false;try{
  if(action.kind==="start"){const id=await arena.start(action.request);if(current()){setAttempt(id);setView(null);setPrepared(null);setConsent(false);setDirty(false);}}
  if(action.kind==="adopt"){await execution.prepare(action.request);await execution.adopt({...context,actionId:action.request.actionId});committed=true;if(current())setNotice("saved");await refreshResult(current);}
  if(action.kind==="compare"){const next=await arena.compare(action.request);if(current()){setComparison(next);setSavedComparisons(old=>[next,...old.filter(v=>v.comparisonId!==next.comparisonId)]);setDirty(false);}}
  if(action.kind==="reveal"){await arena.reveal(action.request);committed=true;await refreshResult(current);}
  if(action.kind==="cancel"){await execution.cancel(action.request);committed=true;if(current())setNotice("cancelled");await refreshResult(current);}
  if(action.kind==="select"){await translations.select(action.request);committed=true;if(current())setNotice("selected");await refreshResult(current);}
  if(action.kind==="merge"){await arena.merge(action.request);committed=true;if(current()){if(draftRef.current?.text===action.request.text)setDraft(null);setNotice("merged");}await refreshResult(current);}
  if(current())setPending(null);
 }catch(e){if(committed){if(current())setPending(null);throw {field:"arena-refresh"};}if(current()&&!unknown(e))setPending(null);throw e;}}
 async function reconcile(current:()=>boolean){if(!pending)return;let found=false;
  if(pending.kind==="start"){const next=await arena.read({...context,attemptId:pending.request.attemptId});found=true;if(current()){setAttempt(pending.request.attemptId);setView(next);setPrepared(null);setConsent(false);setDirty(false);}}
  if(pending.kind==="adopt"){found=!!await execution.receipt({...context,actionId:pending.request.actionId});if(found)await refreshResult(current);}
  if(pending.kind==="cancel"){const next=await arena.read({...context,attemptId:pending.attemptId});found=next.detail.items.some(row=>row.status.cancellationRequested);if(current())setView(next);}
  if(pending.kind==="compare"){const comparisons=await arena.comparisons(context);found=comparisons.some(c=>c.comparisonId===pending.request.actionId);if(found){const next=await arena.comparison({...context,comparisonId:pending.request.actionId});if(current())setComparison(next);}}
  if(pending.kind==="merge"||pending.kind==="select"){found=!!await translations.action({...context,unitId:pending.request.unitId,locale:pending.request.locale,actionId:pending.request.actionId});if(found){await refreshResult(current);if(current()&&pending.kind==="merge"&&draftRef.current?.text===pending.request.text)setDraft(null);}}
  if(pending.kind==="reveal"){if(comparison?.comparisonId===pending.request.comparisonId){const next=await arena.comparison({...context,comparisonId:pending.request.comparisonId});found=next.revealed;if(current())setComparison(next);}else {const next=await arena.read({...context,attemptId:pending.request.comparisonId});found=next.revealed;if(current())setView(next);}}
  if(current()){if(found){setPending(null);setNotice("reconciled");}else setRetryReady(true);}
 }
 function editor(target:EditorTarget,targetLocale:string){void allowLeave().then(ok=>{if(ok&&onOpenTranslation(target,targetLocale))setOpen(false);});}
 const fields=[['endpoint','url'],['model','text'],['credentialEnv','text']] as const,numeric=[['maxOutputTokens',1,16384],['maxRetries',0,2],['timeoutSeconds',1,120]] as const;
 return <><WorkbenchPanel open={open} title={t("arena.title")} description={t("arena.description")} className="arena-dialog" onBack={()=>void allowLeave().then(ok=>{if(ok)setOpen(false);})} backDisabled={disabled || busy || !!pending}>
 {displayedFailure?<div role="alert" tabIndex={-1} ref={errorRef}><p>{t(`arena.errors.${displayedFailure}`,{defaultValue:t(`ai.errors.${displayedFailure}`,{defaultValue:t("arena.errors.failed")})})}</p><button disabled={busy||!!pending} onClick={()=>void refreshPage()}>{t("ai.refresh")}</button></div>:null}
 {notice?<p role="status">{t(`arena.${notice}`,{defaultValue:t("arena.reconciled")})}</p>:null}
 <details open={!attempt}><summary>{t("arena.generation")}</summary><fieldset disabled={locked}><legend>{t("arena.schemes")}</legend>
 {config.variants.map((v,slot)=><details key={slot} open={slot<2}><summary>{t("arena.scheme",{defaultValue:enUS.arena.scheme,number:slot+1})}</summary>{fields.map(([key,type])=><label className="field" key={key}>{t(`ai.${key}`)}<input type={type} value={v[key]} aria-label={t("arena.schemeField",{defaultValue:enUS.arena.schemeField,number:slot+1,field:t(`ai.${key}`)})} onChange={e=>variant(slot,key,e.target.value)}/></label>)}<p>{t("ai.credentialHelp")}</p><label className="field">{t("ai.tokenField")}<select value={v.tokenField} onChange={e=>variant(slot,"tokenField",e.target.value)}><option>max_tokens</option><option>max_completion_tokens</option></select></label>{numeric.map(([key,min,max])=><label className="field" key={key}>{t(`ai.${key}`)}<input type="number" min={min} max={max} value={Number.isFinite(v[key])?v[key]:""} onChange={e=>variant(slot,key,e.target.valueAsNumber)}/></label>)}<label><input type="checkbox" checked={v.shareTerms} onChange={e=>variant(slot,"shareTerms",e.target.checked)}/>{t("ai.shareTerms")}</label><label><input type="checkbox" checked={v.shareContext} onChange={e=>variant(slot,"shareContext",e.target.checked)}/>{t("ai.shareContext")}</label></details>)}
 <button disabled={config.variants.length>=4} onClick={()=>changed({...config,variants:[...config.variants,{...defaultAiConfig}]})}>{t("arena.addScheme")}</button><button disabled={config.variants.length<=2} onClick={()=>changed({...config,variants:config.variants.slice(0,-1)})}>{t("arena.removeScheme")}</button>
 <h3>{t("arena.sharedBudget")}</h3>{([['maxItems',1,100],['maxRequests',1,300],['concurrency',1,2]] as const).map(([key,min,max])=><label className="field" key={key}>{t(`ai.${key}`)}<input type="number" min={min} max={max} value={Number.isFinite(config[key])?config[key]:""} onChange={e=>changed({...config,[key]:e.target.valueAsNumber})}/></label>)}
 <label className="field">{t("ai.locale")}<select value={locale} onChange={e=>{setLocale(e.target.value);setHistory(null);setComparison(null);setReferences([]);setPrepared(null);setConsent(false);setDirty(true);}} disabled={!!draft}>{project.metadata.targetLocales.map(l=><option key={l}>{l}</option>)}</select></label><label><input type="checkbox" checked={config.blind} onChange={e=>changed({...config,blind:e.target.checked})}/>{t("arena.blind")}</label>
 <h3>{t("ai.scope",{count:selected.length})}</h3>{page?<ul>{page.rows.map(row=>row.unitId?<li key={row.unitId}><label><input type="checkbox" checked={selected.includes(row.unitId)} onChange={e=>{setSelected(old=>e.target.checked?[...old,row.unitId!]:old.filter(id=>id!==row.unitId));setPrepared(null);setConsent(false);setDirty(true);}}/>{row.occurrence.key}: {row.occurrence.text}</label></li>:null)}</ul>:<p>{t("ai.noSource")}</p>}<button onClick={()=>void refreshPage(0)}>{t("ai.first")}</button>{page?.nextOrdinal!=null?<button onClick={()=>void refreshPage(page.nextOrdinal!)}>{t("ai.next")}</button>:null}
 <button className="primary-button" disabled={!selected.length} onClick={()=>void perform(async current=>{if(!Number.isInteger(config.maxItems)||!Number.isInteger(config.maxRequests)||!Number.isInteger(config.concurrency)||config.variants.some(v=>numeric.some(([key,min,max])=>!Number.isInteger(v[key])||v[key]<min||v[key]>max)))throw {field:"arena-limits"};const next=await arena.preview({...context,config,locale,unitIds:selected});if(current()){setPrepared(next);setConsent(false);}})}>{t("ai.preview")}</button></fieldset></details>
 {prepared?<section><h3>{t("ai.previewTitle")}</h3><p>{t("arena.expanded",{defaultValue:enUS.arena.expanded,count:prepared.preview.items.length,requests:prepared.preview.config.maxRequests,concurrency:prepared.preview.config.concurrency})}</p><p>{t("ai.costUnknown")}</p>{prepared.preview.items.map(({slot,sourceOrder,item})=><article key={`${sourceOrder}:${slot}`}><h4>{t("arena.scheme",{defaultValue:enUS.arena.scheme,number:slot+1})} · {item.nativeKey} → {item.targetLocale}</h4><p>{prepared.preview.config.variants[slot].endpoint} · {prepared.preview.config.variants[slot].model} · direct-translation-1</p><p>{t("ai.limits",{...prepared.preview.config.variants[slot],requests:prepared.preview.config.maxRequests,concurrency:prepared.preview.config.concurrency,tokens:prepared.preview.config.variants[slot].maxOutputTokens,retries:prepared.preview.config.variants[slot].maxRetries,defaultValue:enUS.ai.limits})}</p><pre className="ai-text">{item.sourceText}</pre>{item.terms.map(term=><p key={term.revisionId}>{term.source} → {term.target}</p>)}{item.context?<pre className="ai-text">{item.context.text}</pre>:null}{item.omissions.map(reason=><p key={reason}>{reason.startsWith("term-conflict:")?t("ai.termConflict",{term:reason.slice(14)}):t(`ai.${reason}`,{defaultValue:reason})}</p>)}</article>)}{config.parentAttemptId?<p>{t("arena.repeatCost")}</p>:null}<label><input type="checkbox" disabled={locked} checked={consent} onChange={e=>setConsent(e.target.checked)}/>{t("arena.consent")}</label><button className="primary-button" disabled={locked||!consent} onClick={()=>void perform(current=>mutate({kind:"start",request:{...context,attemptId:prepared.attemptId,digest:prepared.preview.digest,confirmed:true}},current))}>{t("ai.generate")}</button></section>:null}
 {pending?<section role="status"><p>{t("arena.uncertain")}</p><button disabled={busy} onClick={()=>void perform(reconcile)}>{t("ai.reconcile")}</button>{retryReady||pending.kind==="start"?<button disabled={busy} onClick={()=>void perform(current=>mutate(pending,current))}>{t("ai.retrySame")}</button>:null}</section>:null}
 {view?<section><h3>{t("ai.results")}</h3><p>{t("ai.progress",{...view.detail.progress,defaultValue:enUS.ai.progress})}</p>{view.differentInputs?<p>{t("arena.differentInputs")}</p>:null}{view.repeatedSampling?<p>{t("arena.repeatedSampling")}</p>:null}<p>{t("arena.usageSummary",{defaultValue:enUS.arena.usageSummary,input:view.rows.reduce((n,r)=>n+(r.output?.usage?.promptTokens??0),0),output:view.rows.reduce((n,r)=>n+(r.output?.usage?.completionTokens??0),0)})} · {view.rows.some(r=>!r.output?.usage||r.output.usageIncomplete)?t("ai.usageUnknown"):t("arena.reportedOnly")}</p>
 <button disabled={busy||!!pending} onClick={()=>void perform(refreshResult)}>{t("ai.refresh")}</button>{active?<button disabled={busy||!!pending} onClick={()=>void perform(async current=>{await mutate({kind:"cancel",request:{...context,taskId:view.detail.taskId,requestId:await execution.identity(context)},attemptId:view.detail.attemptId},current);})}>{t("ai.cancel")}</button>:<button disabled={busy||!!pending||!!draft} onClick={()=>void perform(async current=>{const s=await arena.read({...context,attemptId:view.detail.attemptId});if(current()){setAttempt(null);setView(null);changed({...config,variants:s.variants??config.variants,parentAttemptId:s.detail.attemptId});setSelected([...new Set(s.rows.map(r=>r.item.unitId))]);setLocale(s.rows[0].item.targetLocale);setNotice("repeatCost");}})}>{t("arena.newRound")}</button>}
 {view.blind&&!view.revealed?<button disabled={busy||!!pending} onClick={()=>void perform(async current=>mutate({kind:"reveal",request:{...context,comparisonId:view.detail.attemptId,actionId:await execution.identity(context)}},current))}>{t("arena.reveal")}</button>:null}
 {[...new Set(view.rows.map(r=>r.sourceOrder))].map(order=><section key={order}><h4>{view.rows.find(r=>r.sourceOrder===order)?.item.nativeKey}</h4><pre className="ai-text">{view.rows.find(r=>r.sourceOrder===order)?.item.sourceText}</pre><div className="arena-columns">{view.rows.filter(r=>r.sourceOrder===order).map(row=>{const status=view.detail.items.find(i=>i.status.itemId===row.itemId)?.status,recovery=view.detail.recovery.units.find(u=>u.itemIds.includes(row.itemId));return <article key={row.itemId}><h5>{t("arena.candidate",{defaultValue:enUS.arena.candidate,label:letter(row.label)})}</h5>{view.variants?<p>{view.variants[row.label].model} · direct-translation-1</p>:null}<p>{t(`ai.states.${status?.execution}`,{defaultValue:status?.execution??""})}</p>{status?.diagnostic?<p>{t(`ai.errors.${status.diagnostic}`,{defaultValue:t("arena.errors.failed")})}</p>:null}{row.output?<><pre className="ai-text">{row.output.text}</pre><p>{row.output.usage?t("ai.usage",{...row.output.usage,defaultValue:enUS.ai.usage}):t("ai.usageUnknown")}</p><button disabled={busy||!!pending||status?.adoption==="committed"||status?.cancellationRequested||!recovery?.actions.includes("adopt-result")} onClick={()=>void perform(async current=>mutate({kind:"adopt",request:{...context,attemptId:view.detail.attemptId,unitId:recovery!.unitId,actionId:await execution.identity(context),resultIds:[row.resultId!]}},current))}>{status?.adoption==="committed"?t("ai.saved"):t("ai.saveCandidate")}</button></>:null}</article>;})}</div><button disabled={busy||!!pending} onClick={()=>{const item=view.rows.find(r=>r.sourceOrder===order)!.item;editor(aiTarget(item),item.targetLocale);}}>{t("ai.openEditor")}</button></section>)}<p>{t("ai.noAutomaticRetry")}</p></section>:null}
 <section><h3>{t("arena.savedComparison")}</h3><p>{t("arena.offline")}</p><label className="field">{t("arena.original")}<select value={unit} disabled={busy||!!pending||!!draft} onChange={e=>void loadHistory(e.target.value)}><option value="">{t("arena.chooseOriginal")}</option>{page?.rows.map(row=>row.unitId?<option key={row.unitId} value={row.unitId}>{row.occurrence.key}</option>:null)}</select></label><label className="field">{t("ai.locale")}<select value={locale} disabled={busy||!!pending||!!draft||active||!!prepared} onChange={e=>{setLocale(e.target.value);setHistory(null);setComparison(null);setReferences([]);}}>{project.metadata.targetLocales.map(l=><option key={l}>{l}</option>)}</select></label><button disabled={busy||!!pending||!unit||!!draft} onClick={()=>void loadHistory(unit)}>{t("arena.loadCandidates")}</button>
 {history?<><p>{t("arena.chooseCandidates")}</p>{history.rows.map(row=><label className="arena-history" key={row.revisionId}><input type="checkbox" disabled={busy||!!pending||!!draft||(!references.includes(row.revisionId)&&references.length>=4)} checked={references.includes(row.revisionId)} onChange={e=>{setReferences(old=>e.target.checked?[...old,row.revisionId]:old.filter(id=>id!==row.revisionId));setDirty(true);}}/><span>{t("arena.revision",{defaultValue:enUS.arena.revision,number:row.ordinal})} · {row.text}</span></label>)}{history.nextOrdinal!=null?<button disabled={busy||!!pending||!!draft} onClick={()=>void loadHistory(unit,history.nextOrdinal!)}>{t("arena.moreCandidates")}</button>:null}<label><input type="checkbox" disabled={busy||!!pending||!!draft} checked={comparisonBlind} onChange={e=>{setComparisonBlind(e.target.checked);setDirty(true);}}/>{t("arena.blind")}</label><button disabled={busy||!!pending||!!draft||references.length<2} onClick={()=>void perform(async current=>mutate({kind:"compare",request:{...context,actionId:await execution.identity(context),unitId:unit,locale,revisionIds:references,blind:comparisonBlind}},current))}>{t("arena.compare")}</button></>:null}
 {savedComparisons.map(c=><button key={c.comparisonId} disabled={busy||!!pending||!!draft} onClick={()=>void perform(async current=>{const next=await arena.comparison({...context,comparisonId:c.comparisonId!});if(current())setComparison(next);})}>{t("arena.reopen",{defaultValue:enUS.arena.reopen,name:c.nativeKey,locale:c.locale})}</button>)}
 {comparison?<section><h4>{comparison.nativeKey} → {comparison.locale}</h4><pre className="ai-text">{comparison.sourceText}</pre><p>{t("arena.current",{defaultValue:enUS.arena.current,text:comparison.selectedText??t("translation.noSelection")})}</p><p>{t("arena.historical")}</p>{comparison.blind&&!comparison.revealed?<button disabled={busy||!!pending} onClick={()=>void perform(async current=>mutate({kind:"reveal",request:{...context,comparisonId:comparison.comparisonId!,actionId:await execution.identity(context)}},current))}>{t("arena.reveal")}</button>:null}<div className="arena-columns">{comparison.rows.map((row,i)=><article key={row.revisionId}><h5>{t("arena.candidate",{defaultValue:enUS.arena.candidate,label:letter(i)})}</h5><pre className="ai-text">{row.text}</pre><p>{row.basisCurrent?t("arena.currentBasis"):t("arena.oldBasis")}</p>{comparison.revealed?<p>{row.model??(row.originKind==="ai"?t("ai.origin"):row.originKind==="manual"?t("translation.manualOrigin"):t("translation.importOrigin",{file:""}))} {row.recipe??""}</p>:null}<button disabled={busy||!!pending||row.sourceRevisionId!==comparison.sourceRevisionId} onClick={()=>void perform(async current=>mutate({kind:"select",request:{...context,actionId:await execution.identity(context),unitId:comparison.unitId,locale:comparison.locale,sourceRevisionId:comparison.sourceRevisionId,expectedSelectionId:comparison.selectionId,revisionId:row.revisionId}},current))}>{t("arena.use")}</button></article>)}</div><button disabled={busy||!!pending||!!draft||comparison.rows.some(r=>r.sourceRevisionId!==comparison.sourceRevisionId)} onClick={()=>setDraft({basis:comparison,text:comparison.rows[0].text})}>{t("arena.manualMerge")}</button><button disabled={busy||!!pending} onClick={()=>void perform(refreshResult)}>{t("ai.refresh")}</button></section>:null}
 {draft?<section><h3>{t("arena.manualMerge")}</h3><p>{t("arena.mergeHelp")}</p><label className="field">{t("arena.mergedText")}<textarea value={draft.text} onChange={e=>setDraft(d=>d?{...d,text:e.target.value}:null)}/></label><button className="primary-button" disabled={busy||!!pending||!draft.text.trim()} onClick={()=>void perform(async current=>mutate({kind:"merge",request:{...context,actionId:await execution.identity(context),unitId:draft.basis.unitId,locale:draft.basis.locale,sourceRevisionId:draft.basis.sourceRevisionId,expectedSelectionId:draft.basis.selectionId,text:draft.text,merge:{contributors:draft.basis.rows.map(r=>r.revisionId),expectedBasis:draft.basis.basis}}},current))}>{t("arena.saveMerge")}</button><button disabled={busy||!!pending} onClick={()=>void perform(async current=>{const next=await arena.comparison({...context,comparisonId:draft.basis.comparisonId!});if(current())setDraft(d=>d?{...d,basis:next}:null);})}>{t("arena.refreshBasis")}</button><button disabled={busy||!!pending} onClick={()=>setDraft(null)}>{t("arena.discardMerge")}</button></section>:null}</section>
 </WorkbenchPanel>
 <Dialog.Root open={leaving} onOpenChange={next=>{if(!next)settleLeave(false);}}><Dialog.Portal><Dialog.Overlay className="dialog-backdrop execution-confirm-backdrop"/><Dialog.Content className="confirm-dialog execution-confirm-dialog"><Dialog.Title>{t("arena.unsaved")}</Dialog.Title><Dialog.Description>{t("arena.unsavedHelp")}</Dialog.Description><button onClick={()=>settleLeave(false)}>{t("ai.stay")}</button><button onClick={()=>settleLeave(true)}>{t("ai.discard")}</button></Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
